### ISSUE TITLE
Genesis 3:6

### ISSUE THREAD

**Issue by pjoakes** [Door43/ulb-en#454] opened 2017-01-16 17:56 UTC
I would like to purge the ULB of sentence-beginning "And." That is bad English style, and not necessary.  Instead of:
\v 6 **And** when the woman saw that the tree was good for food, and that it was a delight to the eyes, and that the tree was desirable to make one wise, she took some of its fruit and ate it. **And** she gave some also to her husband who was with her, and he ate it.
This:
\v 6 **When** the woman saw that the tree was good for food, and that it was a delight to the eyes, and that the tree was desirable to make one wise, she took some of its fruit and ate it. **Then** she gave some also to her husband who was with her, and he ate it.

**Comment by TomWarren** [comment] 2017-01-16 20:55
The ULB of GEN 3;6 now reads:
\v 6 When the woman saw that the tree was good for food, and that it was a delight to the eyes, and that the tree was desirable to make one wise, she took some of its fruit and ate it. She gave some also to her husband who was with her, and he ate it.

There are 1,137 occurrences of the initial "And ..." in the ULB. This will take some time. 
Thanks, 
TW

**Comment by pohlig** [comment] 2017-01-17 14:07
I agree with Perry. In general, I tried in Phase One of the text project to remove the sentence-initial instances of "And." But I see I missed some.
The choice to often replace "And" with a more suitable English conjunction, as Perry did when he substituted "Then" for "And," is reasonable but not without its own problems. Nevertheless, I guess this is really the best way to go, in order to keep our written English style from becoming too abrupt, too jerky.
Recognize, of course, that this widespread editing of the ULB will result in a lot of miscompares between ULB text and the quoted snippets in the translation notes. To identify these miscompares, we can rely on Dave Statezni, but to remedy the miscompares, we'll have to edit the individual translation notes.

**Comment by ChrisJarka** [comment] 2017-01-17 14:11
Gentlemen - is this something that needs to be addressed before March 30th?

**Comment by TomWarren** [comment] 2017-01-17 14:31
Here are some suggestions for resolving the initial "And ..." 
1. Remove "And and capitalize the next word.
2. Keep the and and conjoin the two sentences.
3. Use "Then ... "
4. Use "Now ... "
5. Use "While ... "
6. Keep the "And ... " in rare cases where this seems to fit context. 

The problem is the translationNotes snippets. 
If I could do 100/ day, I could check the snippets WHILE I am making changes. 
BUT I do not have permission to edit the NT Notes (Susan Quigley has permission). If I could get permission, I could change the snippets along the way, and not touch the Notes, per se.

In this way I could get through this in about 15 days or so.

**Comment by pjoakes** [comment] 2017-01-17 15:09
Who gives these permissions? Is it Jesse?

**Comment by TomWarren** [comment] 2017-01-17 16:21
By far the most time-consuming aspect is checking the snippets in the tN.  
You may check my work by looking at the latest History in Github. 
Suggestions would be appreciated. 

TW

I have gone through Genesis making changes. 
This is the "before" list that I worked from in GitHub:
C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\01.usfm (1 hit)
	Line 31: \v 14 God said, "Let there be lights in the sky to divide the day from the night. And let them be as signs, for seasons, for days and years.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\07.usfm (1 hit)
	Line 7: \v 2 Of every clean animal you will bring with you seven males and seven females. And of the animals that are not clean, bring two, the male and his mate.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\09.usfm (1 hit)
	Line 43: \v 18 The sons of Noah that came out of the ark were Shem, Ham, and Japheth. And Ham was the father of Canaan.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\13.usfm (1 hit)
	Line 35: \v 16 And I will make your descendants as abundant as the dust of the earth, so that if a man could count the dust of the earth, then your descendants could also be counted.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\16.usfm (2 hits)
	Line 9: \v 4 So he had relations with Hagar, and she conceived. And when she saw that she had conceived, she looked with contempt on her mistress.
	Line 18: \v 8 He said, "Hagar, Sarai's servant, where did you come from and where are you going?" And she said, "I am fleeing from my mistress Sarai."
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\17.usfm (2 hits)
	Line 36: \v 17 Then Abraham bowed low with his face to the ground, and laughed, and said in his heart, "Can a child be born to a man who is a hundred years old? And can Sarah, who is ninety years old, bear a son?"
	Line 51: \v 25 And Ishmael his son was thirteen years old when he was circumcised in the flesh of his foreskin.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\18.usfm (3 hits)
	Line 12: \v 5 Let me bring a little food, so that you may refresh yourselves. Afterwards you can go your way, since you have come to your servant." And they said, "Do as you have said."
	Line 56: \v 28 What if there are five less than fifty righteous? Will you destroy the whole city for lack of five?" And he said, "I will not destroy it, if I find there forty-five."
	Line 64: \v 32 He said, "Please do not be angry, Lord, and I will speak this one last time. Perhaps ten will be found there." And he said, "I will not destroy it for the ten's sake."
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\19.usfm (1 hit)
	Line 7: \v 2 He said, "Please my masters, I urge you to turn aside into your servant's house, stay for the night, and wash your feet. Then you can rise up early and go on your way." And they said, "No, we will spend the night in the town square."
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\24.usfm (1 hit)
	Line 62: \v 31 And Laban said, "Come, you blessed of Yahweh. Why are you standing outside? I have prepared the house, and a place for the camels."
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\25.usfm (1 hit)
	Line 55: \v 25 And the first came out red all over like a hairy garment. They called his name Esau.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\26.usfm (1 hit)
	Line 62: \v 28 And they said, "We have clearly seen that Yahweh has been with you. So we decided that there should be an oath between us, yes, between us and you. So let us make a covenant with you,
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\27.usfm (3 hits)
	Line 51: \v 24 He said, "Are you really my son Esau?" And he said, "I am."
	Line 84: \v 36 Esau said, "Is he not rightly named Jacob? For he has cheated me these two times. He took away my birthright, and, see, now he has taken away my blessing." And he said, "Have you not reserved a blessing for me?"
	Line 85: \v 37 Isaac answered and said to Esau, "Look, I have made him your master, and I have given to him all his brothers as servants. And I have given him grain and new wine. What more can I do for you, my son?"
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\29.usfm (1 hit)
	Line 11: \v 4 Jacob said to them, "My brothers, where are you from?" And they said, "We are from Haran."
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\31.usfm (2 hits)
	Line 17: \v 8 If he said, 'The speckled animals will be your wages,' then all the flock bore speckled young. And if he said, 'The striped will be your wages,' then the whole flock bore striped young.
	Line 60: \v 30 And now, you have gone away because you longed very much for your father's house. But why have you stolen my gods?"
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\32.usfm (2 hits)
	Line 36: \v 17 He instructed the first servant, saying, "When Esau my brother meets you and asks you, saying, 'To whom do you belong? Where are you going? And whose are these animals in front of you?'
	Line 37: \v 18 Then you will say, 'They are your servant Jacob's. They are a gift sent to my master Esau. And see, he is also coming after us.'"
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\37.usfm (1 hit)
	Line 65: \v 30 He returned to his brothers and said, "Where is the boy? And I, where will I go?"
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\38.usfm (2 hits)
	Line 38: \v 18 He said, "What pledge can I give you?" And she said, "Your seal and cord, and the staff that is in your hand." He gave them to her and slept with her. She became pregnant by him.
	Line 60: \v 29 It came about as he drew back his hand, behold, his brother came out first. The midwife said, "How you have broken out." And he was named Perez.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\41.usfm (1 hit)
	Line 55: \v 27 And the seven thin and undesirable cows that came up after them are seven years, and also the seven thin heads scorched by the east wind will be seven years of famine.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\42.usfm (1 hit)
	Line 53: \v 28 He said to his brothers, "My money has been put back. Look at it; it is in my sack." And their hearts sank and they turned trembling to one another. They said, "What is this that God has done to us?"
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\43.usfm (1 hit)
	Line 58: \v 29 When he lifted up his eyes he saw Benjamin his brother, his mother's son, and he said, "Is this your youngest brother of whom you spoke to me?" And then he said, "May God be gracious to you, my son."
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\44.usfm (11 hits)
	Line 43: \v 20 And we said to my master, 'We have a father, an old man, and a child of his old age, a little one. And his brother is dead, and he alone is left of his mother, and his father loves him.'
	Line 43: \v 20 And we said to my master, 'We have a father, an old man, and a child of his old age, a little one. And his brother is dead, and he alone is left of his mother, and his father loves him.'
	Line 44: \v 21 And you said to your servants, 'Bring him down to me that I may see him.'
	Line 45: \v 22 And we said to my master, 'The boy cannot leave his father. For if he should leave his father his father would die.'
	Line 48: \v 23 And you said to your servants, 'Unless your youngest brother comes down with you, you will not see my face again.'
	Line 49: \v 24 And it came about when we went up to your servant my father, we told him the words of my master.
	Line 50: \v 25 And our father said, 'Go again, buy us some food.'
	Line 51: \v 26 And we said, 'We cannot go down. If our youngest brother is with us, then will we go down, for we will not be able to see the man's face unless our youngest brother is with us.'
	Line 55: \v 28 And the one went out from me and I said, "Surely he is torn in pieces, and I have not seen him since."
	Line 56: \v 29 And if you take this one also from me and harm comes to him, you will bring down my gray hair with sorrow to Sheol.'
	Line 60: \v 31 it will come about, when he sees that the boy is not with us that he will die. And your servants will bring down the gray hair of your servant our father with sorrow to Sheol.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\45.usfm (2 hits)
	Line 12: \v 5 And now do not be grieved or angry with yourselves that you sold me here, for God sent me ahead of you to preserve life.
	Line 50: \v 26 They told him saying "Joseph is still alive, and he is ruler over all the land of Egypt." And his heart was astonished, for he did not believe them.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\46.usfm (2 hits)
	Line 9: \v 4 I will go down with you into Egypt, and I will surely bring you up again. And Joseph will close your eyes with his own hand."
	Line 24: \v 12 The sons of Judah: Er, Onan, Shelah, Perez, and Zerah, (but Er and Onan had died in the land of Canaan). And the sons of Perez were Hezron and Hamul.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\48.usfm (1 hit)
	Line 14: \v 5 And now your two sons, who were born to you in the land of Egypt before I came to you into Egypt, they are mine. Ephraim and Manasseh will be mine, just as Reuben and Simeon are mine.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\01-GEN\50.usfm (1 hit)
	Line 38: \v 20 And as for you, you meant to harm me, but God meant it for good, to preserve the lives of many people, as you see today.
Search "And " (1137 hits in 505 files)

**Comment by pjoakes** [comment] 2017-01-17 17:16
Tom, I like your suggestions for resolving the initial "And."
Chris, I see no problem with Tom editing the snippet to match the ULB edit, since this is not the Note itself.

**Comment by ChrisJarka** [comment] 2017-01-17 17:47
There is already a process in place for correcting the tNs after the ULB has been changed.
We have someone that runs a mis-compare batch file weekly. This run finds all the mis-compares between the tN snippet and the ULB text.  This assures us that all mis-compares are caught.
The people assigned with the job to correct the notes go through the mis-compare file correcting the snippet and then assuring that the explanation of the snippet (tN) aligns with the new change. There are times when a correction to the snippet is not all that needs to be done. 
If the snippets are corrected at the same time as the ULB - the extra step of checking the tN might not be done.

Please, will the text team allow the Notes team to complete the process as it is already set in place?

**Comment by TomWarren** [comment] 2017-01-17 18:14
From the experiment on Genesis, there about 45 changes to "And" in ULB text, and only about 5 places in the Notes where the changes I made touched the snippets (that the quote from the ULB was no longer exactly like the snippet, and the change was made with little trouble. No change that involved the snippet touched the meaning of the note. 
It would be much quicker for me just to make the changes in the ULB, and someone else do the check of snippets, but there is the double-check benefit of me going through the notes and being sure that the were not other points of confusion in the text that would need to be edited (outside and not touching the notes).
Checking the notes took a lot of time. Finding the few that needed to have the snippet changed took very little time.

**Closed** 2017-01-18 14:35 UTC
